CREATE DATABASE IF NOT EXISTS db_clientes;
CREATE DATABASE IF NOT EXISTS db_catalogo;
CREATE DATABASE IF NOT EXISTS db_pedidos;
CREATE DATABASE IF NOT EXISTS db_delivery;
CREATE DATABASE IF NOT EXISTS db_cupones;
CREATE DATABASE IF NOT EXISTS db_inventario;
CREATE DATABASE IF NOT EXISTS db_pagos;
CREATE DATABASE IF NOT EXISTS db_proveedores;
