server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          # Ruta donde guardarás tus configuraciones globales si usas native
          search-locations: classpath:/config-microservicios
  profiles:
    active: native